# Podstawy Sztucznej Inteligencji 2020/2021


Prosze uzupelnic kod tam gdzie znajduje napis `YOUR CODE HERE` lub 'YOUR ANSWER HERE'.

Warto zresetowac 'kernel' i sprawdzic czy caly notatnik uruchamiany od poczatku nie daje bledow.

---

## Zaimportuj moduł  numpy  do przestrzeni nazw `np` 

In [1]:
import numpy as np

In [2]:
from types import ModuleType
assert type(globals()['np']) == ModuleType

## Stwórz wektor zer o rozmiarze 12

In [47]:
v = np.zeros(12)

In [48]:
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
assert v.sum() == 0
assert v.shape == (12,)

##  Napisz funkcję zwracającą ilość bajtów jaką zajmują dane w tablicy numpy

In [50]:
def memof(a):
    return a.nbytes

In [51]:
memof(v)

96

In [52]:
assert memof(np.zeros((12,10),dtype=np.int32))==480

In [53]:
print(memof(np.zeros((12,10),dtype=np.int32)))

480


## Napisz funkcję tworzącą wektor zer o rozmiarze `n` z jedynką na piątym miejscu

In [9]:
def make_v(n):
    v = np.zeros(n)
    v[4] = 1
    return v

In [55]:
make_v(8)

array([0., 0., 0., 0., 1., 0., 0., 0.])

In [10]:
assert make_v(14)[4] == 1
np.testing.assert_array_equal( make_v(14)[:4] , 0)
np.testing.assert_array_equal( make_v(14)[5:] , 0)


## Utwórz wektor z wartościami od 10 do 29 włącznie

In [11]:
def make10_29():
    arr = np.arange(10, 30)
    return arr

In [57]:
make10_29()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [58]:
assert make10_29()[7] == 17
assert np.sum(make10_29()) == 390

## Odwóć kolejność elementów wektora

In [67]:
def reverse(v):
    return np.flip(v)

In [68]:
reverse(make_v(8))

array([0., 0., 0., 1., 0., 0., 0., 0.])

In [69]:
np.testing.assert_equal(reverse(np.array([1,2,3])), np.array([3,2,1]) )

## Stwórz macierz jednostkową o rozmiarze $n \times n$



In [16]:
def identity_matrix(n=3):
    return np.identity(n)

In [71]:
identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.testing.assert_equal( identity_matrix(2), np.array([[1, 0],  [0, 1]]) )


## Utwórz macierz $n\times n$  z  wartościami od $1$ do $n^2$

 - tak by każdy rząd zawierał wartości rosnące o 1
 - tak by każda kolumna zawierała wartości rosnące o 1

In [84]:
def n2_col(n=3):
    col = np.arange(1, n**2 + 1).reshape(n, n)
    return col

def n2_row(n=3):
    row = np.arange(1, n**2 + 1).reshape(n, n)
    return row.T

In [85]:
# test
print(n2_col())
print()
print(n2_row())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [86]:
np.testing.assert_equal( n2_col(2), np.array([[1, 2],  [3, 4]]) )
np.testing.assert_equal( n2_row(2), np.array([[1, 3],  [2, 4]]) )


## Utwórz macierz $n\times m$  z  losowymi wartościami 

- z przedziału [0,1)
- z przedziału [a,b)

In [95]:
def rand1(n=3, m=4):
    return np.random.random(size=(n, m))

def rand2(n=3, m=4, a=6, b=7):
    return np.random.randint(a, b, size=(n, m))

In [97]:
# test
print(rand1())
print()
print(rand2(a=1, b=10))

[[0.78070242 0.75128074 0.65489296 0.39705577]
 [0.84024785 0.12956789 0.89721097 0.47924681]
 [0.15590305 0.20334754 0.81861061 0.93587942]]

[[2 1 6 5]
 [7 4 3 5]
 [6 6 1 3]]


In [93]:
assert np.min(rand1(10, 11)) >= 0
assert np.max(rand1(10, 10)) < 1
assert np.min(rand2(10, 12, 3,7)) >= 3
assert np.max(rand2(10, 12, 3,7)) < 7
assert np.shape(rand2(10, 12, 3,7)) == (10, 12)
assert np.shape(rand1(10, 15)) == (10, 15)

## Znajdź indeksy dla których wartości wektora są równe zero

In [103]:
def is_zero(x):
    zeros = np.where(x == 0)[0]
    return zeros

In [100]:
x = np.array([1,2,0,1,0,11])
np.testing.assert_equal(is_zero(x), np.array([2,4]) ) 

In [106]:
is_zero(x)

array([2, 4])

In [109]:
def is_zero_v2(x):
    return np.argwhere(x == 0)

In [110]:
is_zero_v2(x)

array([[2],
       [4]])

In [101]:
def is_zero_true_or_false(x):
    return x != 0

print(is_zero_trueorfalse(x))

[ True  True False  True False  True]


## Oblicz dla zadanego wektora jego wartość najmniejszą, największą oraz średnią.

In [27]:
def mystats(x):
    return np.amin(x), np.amax(x), np.mean(x)

In [28]:
x = np.array([1,2,0,1,0,11])
assert  mystats(x) == (0, 11, 2.5) 

In [111]:
mystats(x)

(0, 11, 2.5)

## Stwórz dwuwymiarową tablicę z zerami w środku i jedynkami na zewnątrz

In [113]:
def zeros_padded(n=4):
    arr = np.zeros((n-2, n-2))
    arr_padded = np.pad(arr, 1, mode='constant', constant_values=1)
    return arr_padded

In [116]:
zeros_padded(8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [117]:
np.testing.assert_equal(zeros_padded(4) , 
np.array([[ 1.,  1.,  1.,  1.],
         [ 1.,  0.,  0.,  1.],
         [ 1.,  0.,  0.,  1.],
         [ 1.,  1.,  1.,  1.]]))



## Używając `np.pad` dodaj do tablicy otoczenie z wartością 3

In [118]:
def pad3(x):
    return np.pad(x, 1, mode='constant', constant_values=3)

In [121]:
x = np.ones((6, 3))
pad3(x)

array([[3., 3., 3., 3., 3.],
       [3., 1., 1., 1., 3.],
       [3., 1., 1., 1., 3.],
       [3., 1., 1., 1., 3.],
       [3., 1., 1., 1., 3.],
       [3., 1., 1., 1., 3.],
       [3., 1., 1., 1., 3.],
       [3., 3., 3., 3., 3.]])

In [32]:
x = np.ones((2,3))
x_pad3 = np.array([[ 3.,  3.,  3.,  3.,  3.],
                   [ 3.,  1.,  1.,  1.,  3.],
                   [ 3.,  1.,  1.,  1.,  3.],
                   [ 3.,  3.,  3.,  3.,  3.]])            
np.testing.assert_equal( pad3(x),x_pad3)

## Dla danej tablicy zastąp maksymalne wartości zerami


In [33]:
def maxto0(x):
    size = np.shape(x)
    #print(size)
    
    flat_x = x.flat[:]
    #print(flattened)
    
    flat_x = np.where(flat_x == np.max(flat_x), 0, flat_x)
    x = flat_x.reshape(size)
    
    return x

In [122]:
x_expected = np.array([[1, 3, 1, 2],
                       [0, 2, 1, 0],
                       [2, 0, 2, 1]])

maxto0(x_expected)

array([[1, 0, 1, 2],
       [0, 2, 1, 0],
       [2, 0, 2, 1]])

In [123]:
def maxto0_v2(x):
    temp = np.amax(x)
    #print(temp)
    return np.where(x == temp, 0, x)

In [124]:
x_expected = np.array([[1, 3, 1, 2],
                       [0, 2, 1, 0],
                       [2, 0, 2, 1]])

maxto0_v2(x_expected)

array([[1, 0, 1, 2],
       [0, 2, 1, 0],
       [2, 0, 2, 1]])

In [125]:
x_expected = np.array([[1, 0, 1, 2],
                       [0, 2, 1, 0],
                       [2, 0, 2, 1]])

x = np.array([[1, 3, 1, 2],
                   [3, 2, 1, 3],
                   [2, 0, 2, 1]])
np.testing.assert_equal(maxto0(x),x_expected)

## Broadcasting

Niech będzie dana tablica  $k$ parametrów  zmierzonych w  $n$  pomiarach: 

 - $ x_{ij} $: $j$-ty parametr w $i$-tym pomiarze

Oblicz korzystając z ``numpy`` nie używając pętli:

 - średnią po pomiarach dla wszyskich zmiennych: $$\mu_j = \frac{1}{n} \sum_{i=1}^n x_{ij}$$
 - odchylenie od wartości średniej dla każdej zmiennej we wszystkich pomiarach:$$\Delta_{ij} = x_{ij}-\mu_j$$
 - odchylenie średniokwadratowe dla każdej zmiennej: $$\sigma_j^2 = \frac{1}{n} \sum_{j=1}^n (x_{ij}-\mu_j)^2$$
 

In [126]:
def data_stats(x):
    x_avg = np.sum(x, axis=0) / x.shape[0]
    Delta = x - x_avg
    sigma = np.sum((x - x_avg)**2, axis=0) / x.shape[0]
    
    return x_avg, Delta, sigma

In [130]:
x = np.array([[1, 3, 1, 2], [3, 2, 1, 3], [2, 0, 2, 1]])

data_stats(x)

(array([2.        , 1.66666667, 1.33333333, 2.        ]),
 array([[-1.        ,  1.33333333, -0.33333333,  0.        ],
        [ 1.        ,  0.33333333, -0.33333333,  1.        ],
        [ 0.        , -1.66666667,  0.66666667, -1.        ]]),
 array([0.66666667, 1.55555556, 0.22222222, 0.66666667]))

In [134]:
data_stats(x)[0]  # x_avg

array([3.2, 3. , 2.2, 2.4])

In [135]:
data_stats(x)[1]  # Delta

array([[-0.2,  1. , -0.2,  0.6],
       [-0.2,  1. ,  0.8,  1.6],
       [ 0.8,  0. , -0.2, -0.4],
       [-0.2, -1. , -1.2, -0.4],
       [-0.2, -1. ,  0.8, -1.4]])

In [136]:
data_stats(x)[2]  # sigma

array([0.16, 0.8 , 0.56, 1.04])

In [131]:
x = np.array([[3, 4, 2, 3],
       [3, 4, 3, 4],
       [4, 3, 2, 2],
       [3, 2, 1, 2],
       [3, 2, 3, 1]])
x_avg,Delta,sigma = data_stats(x)


np.testing.assert_allclose(x_avg,np.array([ 3.2,  3. ,  2.2,  2.4]))
np.testing.assert_allclose(Delta,\
  np.array([[-0.2,  1. , -0.2,  0.6],
           [-0.2,  1. ,  0.8,  1.6],
           [ 0.8,  0. , -0.2, -0.4],
           [-0.2, -1. , -1.2, -0.4],
           [-0.2, -1. ,  0.8, -1.4]]) )                           
np.testing.assert_allclose(sigma,np.array([ 0.16,  0.8 ,  0.56,  1.04]))

import inspect
blacklist = [".mean",".average","for","while","std",'var']
assert all([ not keyword  in inspect.getsource(data_stats) for keyword in blacklist])
