# Podstawy Sztucznej Inteligencji 2020/2021


Prosze uzupelnic kod tam gdzie znajduje napis `YOUR CODE HERE` lub 'YOUR ANSWER HERE'.

Warto zresetowac 'kernel' i sprawdzic czy caly notatnik uruchamiany od poczatku nie daje bledow.

---

## Iloczyn skalarny

Mając wektory $n$-elementowe $\mathbf{a}$ i $\mathbf{b}$ napisać funkcję obliczającą ich iloczyn skalarny:

$$s =\mathbf{a}\cdot \mathbf{b} =  \sum_{i=1}^{n} a_i b_i $$ 

 - za pomocą iteracji po elementach
 - używając funkcjonalności `numpy`

In [474]:
import numpy as np

In [475]:
def s1(a, b):
    if len(a) != len(b):
        raise ValueError("Wektory o różnych wymiarach")
        
    temp = []
    for i in range(len(a)):
        temp.append(a[i] * b[i])
    return sum(temp)


def s2(a, b):
    if len(a) != len(b):
        raise ValueError("Wektory o różnych wymiarach")
    
    return np.dot(a, b)

In [476]:
def s1_v2(a, b):
    if len(a) != len(b):
        raise ValueError("Wektory o różnych wymiarach")
    
    return sum([i*j for i, j in zip(a, b)])

In [477]:
assert s1([1,1,1,1],[1,1,1,1]) == 4 
assert s2([1,1,1,1],[1,1,1,1]) == 4
assert np.isscalar(s2([1,1,1,1],[1,1,1,1]))
assert np.isscalar(s1([1,1,1,1],[1,1,1,1]))
assert s2([7,7,7],[7,7,7]) == 147
assert s1([7,7,7],[7,7,7]) == 147

## Mnożenie macierzy przez wektor:

Mając wektor $n$-elementowy $\mathbf{x}$ oraz macierz $\mathbf{A}$ o wymiarach $m\times n$ napisać funkcję obliczającą ich iloczyn:

$$\mathbf{y}= \mathbf{A}\mathbf{x}.$$

Każdy element wektora $\mathbf{y}$ jest dany przez:

$$y_i = \sum_{j=1}^{n} a_{ij} x_j $$ 

 - za pomocą iteracji po elementach (podwójna pętla)
 - korzystając z faktu, że
 każdy element wektora $y_i$ jest iloczynem skalarnym $i$-tego rzędu macierzy $\mathbf A$ oraz wektora $\mathbf{x}$ (pojedyncza pętla)
 - używając funkcji:  `np.dot` lub `np.tensordot` (bez pętli)


In [478]:
def y1(A,x):
    #print(np.shape(A)[1], np.shape(x)[0])
    if np.shape(A)[1] != np.shape(x)[0]:
        raise ValueError("Drugi wymiar macierzy nie jest równy wymiarowi wektora")
    
    temp = []
    wynik = []
    
    for i in range(len(A)):
        for j in range(len(x)):
            temp.append(A[i][j] * x[j])
        suma = sum(temp)
        wynik.append(suma)
        temp.clear()
        
    return np.array(wynik)


def y2(A,x):
    if np.shape(A)[1] != np.shape(x)[0]:
        raise ValueError("Drugi wymiar macierzy nie jest równy wymiarowi wektora")
        
    temp = []
    
    for i in range(len(A)):
        temp.append(A[i] * x)
    
    arr = np.array(temp)
    column_sums = arr.sum(axis=1)
    return column_sums


def y3(A,x):
    if np.shape(A)[1] != np.shape(x)[0]:
        raise ValueError("Drugi wymiar macierzy nie jest równy wymiarowi wektora")
        
    return np.dot(A, x)

In [479]:
A = np.array([[10, 6, 7], [3, 9, 1], [5, 5, 5]]) 
x = np.array([9, 5, 5])

A, x

(array([[10,  6,  7],
        [ 3,  9,  1],
        [ 5,  5,  5]]), array([9, 5, 5]))

In [480]:
print('y1:', y1(A, x))
print('y2:', y2(A, x))
print('y3:', y3(A, x))

y1: [155  77  95]
y2: [155  77  95]
y3: [155  77  95]


In [481]:
def y1_v2(A, x):
    if np.shape(A)[1] != np.shape(x)[0]:
        raise ValueError("Drugi wymiar macierzy nie jest równy wymiarowi wektora")
        
    for row in A:
        for col in x:
            return [sum([i*j for i, j in zip(z, x)]) for z in A]
        
        
def y2_v2(A, x):
    if np.shape(A)[1] != np.shape(x)[0]:
        raise ValueError("Drugi wymiar macierzy nie jest równy wymiarowi wektora")
        
    temp = []
    for row in A:
        np.dot(row, x)
    return [np.dot(row, x) for row in A]

In [482]:
print('y1:', y1_v2(A, x))
print('y2:', y2_v2(A, x))

y1: [155, 77, 95]
y2: [155, 77, 95]


In [483]:
A = np.arange(12).reshape(3,4)
x = np.arange(4)
np.testing.assert_almost_equal(y1(A,x),np.array([14, 38, 62]))
np.testing.assert_almost_equal(y2(A,x),np.array([14, 38, 62]))
np.testing.assert_almost_equal(y3(A,x),np.array([14, 38, 62]))


In [484]:
try:
    y1(np.arange(9).reshape(3,3),np.array([1,1]))
except ValueError:
    pass
else:
    raise AssertionError("Second dimension of matrix should be the same as dimension of vector!.")

## Mnożenie macierzy

Mamy dwie macierze $\mathbf{A}_{m\times n}$ i $\mathbf{B}_{n\times k}$. Napisać funkcję obliczającą ich iloczyn:

$$\mathbf{C}= \mathbf{A}\mathbf{B}$$.

Każdy element macierzy  $\mathbf{C}$ jest dany przez:

$$c_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj} $$ 

 - za pomocą iteracji po elementach (potrójna pętla)
 - korzystając z faktu, że każdy element macierzy $c_{ij}$ jest iloczynem skalarnym $i$-tego rzędu macierzy $\mathbf A$ oraz  $j$-tego rzędu macierzy $\mathbf B$ (podwójna pętla)
 - używając funkcji:  `np.dot` lub `np.tensordot` (bez pętli)
 

In [485]:
def C1(A,B):
    if np.shape(A)[1] != np.shape(B)[0]:
        raise ValueError("Wymiary macierzy uniemożlwiają ich przemnożenie")

    temp = []
    wynik =[]
    
    for i in range(np.shape(A)[0]):
        for j in range(np.shape(B)[1]):
            for k in range(np.shape(A)[1]):
                #print(A[i][k], B[k][j], A[i][k] * B[k][j])
                temp.append(A[i][k] * B[k][j])
            suma = sum(temp)
            wynik.append(suma)
            temp.clear()
            #print('WYNIK:', wynik)
    
    return np.array(wynik).reshape(np.shape(A)[0], np.shape(B)[1])


# BŁĘDY MŁODOŚCI:
#     temp = []
#     wynik =[]
    
#     for i in range(np.shape(A)[1]):
#         for j in range(np.shape(B)[0]):
#             for k in range(np.shape(A)[0]):
#                 print(A[i][k], B[k][j], A[i][k] * B[k][j])
#                 temp.append(A[i][k] * B[k][j])
#             suma = sum(temp)
#             wynik.append(suma)
#             temp.clear()
    
#     return np.array(wynik).reshape(np.shape(A)[1], np.shape(B)[0])
    
def C2(A,B):
    if np.shape(A)[1] != np.shape(B)[0]:
        raise ValueError("Wymiary macierzy uniemożlwiają ich przemnożenie")
    
    temp = []
    wynik = []
    
    for i in range(np.shape(A)[0]):
        for j in range(np.shape(B)[0]):
            temp.append(A[i][j] * B[j])
    
        suma = sum(temp)
        wynik.append(suma)
        temp.clear()
    
    arr = np.array(wynik)
    return arr


def C3(A,B):
    if np.shape(A)[1] != np.shape(B)[0]:
        raise ValueError("Wymiary macierzy uniemożlwiają ich przemnożenie")
        
    return np.dot(A, B)

In [486]:
A, B = np.ones((4,5)), np.arange(10).reshape(5,2)
print(A, '\n\n', B, '\n')

print(C1(A, B), '\n')
print(C2(A, B), '\n')
print(C3(A, B), '\n')


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[20. 25.]
 [20. 25.]
 [20. 25.]
 [20. 25.]] 

[[20. 25.]
 [20. 25.]
 [20. 25.]
 [20. 25.]] 

[[20. 25.]
 [20. 25.]
 [20. 25.]
 [20. 25.]] 



In [487]:
m = np.arange(9).reshape(3,3)
assert np.prod(C1(np.eye(3),m) == m)
assert np.prod(C1(m,m) == C3(m,m))
assert np.prod(C2(m,m) == C3(m,m))


A,B = np.ones((4,5)),np.arange(10).reshape(5,2)
assert C1(A,B).shape == (4,2)
assert C2(A,B).shape == (4,2)
assert C3(A,B).shape == (4,2)

np.testing.assert_allclose(C1(A,B), A.dot(B))
np.testing.assert_allclose(C2(A,B), A.dot(B))
np.testing.assert_allclose(C3(A,B), A.dot(B))



In [488]:
try:
    C1(np.arange(9).reshape(3,3),np.ones((2,3)))
except ValueError:
    pass
else:
    raise AssertionError("Second dimension of matrix should be the same as dimension of vector!.")

## Ślad macierzy

Śladem macierzy nazywamy sumę elementów na przekątnej: 

$$ Tr(A) = \sum_{i=1}^{n} a_{ii}$$


Obliczyć ślad macierzy $n\times n$.



In [489]:
def Tr(A):
    #print(np.shape(A))
    if np.shape(A)[0] != np.shape(A)[1]:
        raise ValueError
    
    output = 0
    for i in range(len(A)):
        output += A[i][i]
    return output

In [490]:
A1 = np.array([[10, 6, 7], [3, 9, 1], [5, 5, 5]]) 
print(Tr(A1))

24


In [491]:
assert Tr(np.diag([1,2,3,4])) == 10

In [492]:
try:
    Tr(np.ones((2,3)))
except ValueError:
    pass
else:
    raise AssertionError("The matrix should be square matrix!.")

## Wyznacznik macierzy

Obliczyć wyznacznik macierzy korzystając z rozwinięcia [Laplace'a](https://pl.wikipedia.org/wiki/Rozwini%C4%99cie_Laplace%E2%80%99a)


In [493]:
import numpy as np
A = np.random.randint(4,size=(4,4)).astype(np.float)
x = np.random.randint(4,size=4)

In [494]:
print(A, '\n\n', x)

[[0. 3. 2. 0.]
 [3. 2. 2. 3.]
 [0. 1. 3. 2.]
 [2. 2. 3. 3.]] 

 [3 0 0 2]


In [495]:
def Le(A):
    temp = []
    
    if A.shape[0] > 2:
        for j in range(0, A.shape[1]):
            new_A = A[:]
            #print('*1*:\n', new_A, '\n')
            new_A = new_A[1:]
            #print('*2*:\n', new_A, '\n')
            new_A = np.delete(new_A, j, 1)
            #print('*3*:\n', new_A, '\n')
            mult = A[0][j] * ((-1)**(2+j))
            
            det = Le(new_A)
            temp.append(mult * det)
        return sum(temp)
    else:
        return A[0][0]*A[1][1] - A[0][1]*A[1][0]


In [496]:
dett = np.array([[1,1,2],[2,3,4],[3,4,5]])
Le(dett)

-1

In [497]:
A = np.array([[ 1.,  3.,  0.,  0.],[ 3.,  2.,  3.,  2.],[ 1.,  2.,  2.,  2.],[ 1.,  0.,  0.,  3.]])
np.testing.assert_allclose( Le(A), np.linalg.det(A) )