# Podstawy Sztucznej Inteligencji 2020/2021


Prosze uzupelnic kod tam gdzie znajduje napis `YOUR CODE HERE` lub 'YOUR ANSWER HERE'.

Warto zresetowac 'kernel' i sprawdzic czy caly notatnik uruchamiany od poczatku nie daje bledow.

---

## Oblicz normę  wektora

Dla zadanego wektora należy obliczyć:
 - normę $L^1$ 
 - normę $L^2$
 
Oznaczenia $L^{1,2}$ są określone następującym wzorem:


$$ L^p = \left\| \mathbf{x} \right\| _p := \bigg( \sum_{i=1}^n \left| x_i \right| ^p \bigg) ^{1/p}$$

 

In [4]:
import numpy as np 
x = np.random.randn(4)
print(x)

[-0.08152491 -0.93987388  1.11078749 -1.02631241]


In [10]:
L2 = np.sqrt(np.dot(x,x))   

In [14]:
L1 = np.sum(np.abs(x))


In [15]:
assert L2 == np.linalg.norm(x,ord=2)
assert L1 == np.linalg.norm(x,ord=1)

## Własności normy $L^1$ vs. $L^2$

Sprawdźmy na przykładzie wektorów $x_1 = [1,1,1,1,1]$ i $x_2=[0,0,0,0,5]$ ile wynoszą ich normy.
Można zauważyć, że norma $L^1$ nie zmienia się gdy zmienimy wektor $x_2 \to x_1$ a norma $L^2$ maleje. Ma to konsekwencje dla zagadnienia regularyzacji. Dodanie do zagadnienia  minimalizacyjnego członu proporcjonalnego do normy $L^1$ będzie preferowało rozwiązania "rzadkie" norma $L^2$ będzie miała tendencje do wyrównywania parametrów.

In [2]:
for x in [ [1,1,1,1,1],[0,0,0,0,5] ]:
    x = np.array(x)
    print(x,np.linalg.norm(x,ord=2), np.linalg.norm(x,ord=1) )

[1 1 1 1 1] 2.23606797749979 5.0
[0 0 0 0 5] 5.0 5.0


## Wykresy norm

Zobaczmy jak wyglądają wykresy normy wektora dwuwymiarowego w zależności od liczby $p$:

In [ ]:
import matplotlib.pyplot as plt

x,y = np.meshgrid( *(2*(np.linspace(-1,1,100),) ) )

fig, axes = plt.subplots(nrows=1, ncols=4, figsize=(12,3),sharey=True, sharex=True)
for i, ax in enumerate(axes.flat, start=1):
    ax.set(aspect=1)
    if i==4:
        i=100
    ax.set_title(r'$L^{%d}$'%i)
    ax.contourf(x,y,np.linalg.norm(np.stack([x,y]),axis=0,ord=i))


In [ ]:
import matplotlib.pyplot as plt
from ipywidgets import interact, IntSlider
from IPython.display import clear_output

x,y = np.meshgrid( *(2*(np.linspace(-1,1,100),) ) )
p_lst = [1,2,3,4,10,100]
@interact(i=IntSlider(max=len(p_lst)-1))
def _drawnorm(i):
    p = p_lst[i]
    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(3,3))
    ax.set(aspect=1)
    ax.set_title(r'$L^{%d}$'%p)
    ax.contourf(x,y,np.linalg.norm(np.stack([x,y]),axis=0,ord=p))
    clear_output(wait=True)
    